---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: hugo/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: hugo/content/careers
  label: Careers
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/docs
  label: Docs
  create: all
  match: "{{editing,faqs,git-sync,guides,hosting,media,quickstart,settings,troubleshooting,welcome}/**/*,*}"
- type: directory
  path: hugo/content/showcase
  label: Showcase
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/docs/changelog
  label: Changelog
  create: all
  match: "*"
  templates:
  - changelog
upload_dir: hugo/static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
version: 0.42.2
